[package]
name = "virtualcan"
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"
log = "0.4.8"
simple_logger = "1.3.0"
tokio = "0.1.22"